### ISSUE TITLE
Create a Telegram gateway (via Bot)

### ISSUE THREAD

**Issue by niansa** [ehsan-mohammadi/GAPITA#15]
Hi!

It would be really nice to have a telegram bot that connects users ro the chat via telegram! But, Telegram has a lot of spambots. Some way to get rid of them is required.

Nils / niansa

**Comment by ehsan-mohammadi** [comment]
@niansa Hi!
It would be great. But currently, I'm focused on GAPITA website. Also, there are so many Telegram bots that make it possible to chat with random users. But thanks for your offer.
