### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by niansa** [ehsan-mohammadi/GAPITA#16]
Hi, here is a list of my suggestions to make this chat better:

 * Add button to quickly send emojis - should not take to much place and should only appear on computer, because most mobile keyboards have smileys build-in
 * Somehow "answer" to a message by swiping over the message to left or right.
 * Confirmation dialog before leaving chat/closing tab

Nils aka niansa

**Comment by ehsan-mohammadi** [comment]
Hi Nils!
Thanks for your suggestions. These are so good. I'll try to add them in the future and I would be happy if everyone can help to make GAPITA better.

Good luck!

**Comment by ehsan-mohammadi** [comment]
> * Confirmation dialog before leaving chat/closing tab

I added a confirmation dialog that appears when you click on leave chat button. This feature will be added to the site, soon :)

**Comment by hosseinmoazami** [comment]
hi
*stranger seen the message yet or not 
*can use the enter for long message

**Comment by ehsan-mohammadi** [comment]
> * Add button to quickly send emojis - should not take to much place and should only appear on computer, because most mobile keyboards have smileys build-in

#23 **Add emojis**

**Comment by niansa** [comment]
Great work so far!

**Comment by fortiz303** [comment]
How come dotnet run wont work?

**Comment by ehsan-mohammadi** [comment]
@fortiz303 Hi!
Sorry, I can't understand your comment clearly. Can you explain more?
