### ISSUE TITLE
rejoin chat

### ISSUE THREAD

**Issue by m-zare** [ehsan-mohammadi/GAPITA#18]
I was chatting with a guy. Accidentally leave the page and lost the chat.
It would be a good idea to rejoin previous chat.

**Comment by ehsan-mohammadi** [comment]
@m-zare Hi Mostafa!
Thanks for your comment. You can't rejoin to a chat after you left from it. But I'll design a confirmation dialog to avoid accidentally leave :)

**Comment by ehsan-mohammadi** [comment]
#20 **Add leave confirmation dialog**
