### ISSUE TITLE
Block Button

### ISSUE THREAD

**Issue by vahid-saffarian** [ehsan-mohammadi/GAPITA#19]
Hello Ehsan,

great job overall, and especially the sound effect on sending/receiving messages which makes for an appealing user experience. I'd suggest to relocate the block button, since it's close to send button and might happen more often than not to accidentally end a good conversation (:

Regards,
Vahid

**Comment by ehsan-mohammadi** [comment]
@vahid-saffarian Hi Vahid!
Thanks for your comment :)
#18 -> I'll design a confirmation dialog before leaving the chat. Good luck :)

**Comment by ehsan-mohammadi** [comment]
#20 **Add leave confirmation dialog**
