### ISSUE TITLE
Deployed on aws, shows connection refused when accessed from outside.

### ISSUE THREAD

**Issue by webslayer** [ehsan-mohammadi/GAPITA#38]
Any steps to deploy it globally could help.

**Comment by ehsan-mohammadi** [comment]
Hi @webslayer!
Thanks for submitting this issue. You need to enable Cross-Origin requests (CORS). you should set **UserCors** policy to **AllowAll**.

Just do these changes in `Startup.cs` file:

```csharp
 public void Configuration(IAppBuilder app)
{
    app.Map("/signalr", map =>
    {
        map.UseCors(CorsOptions.AllowAll);
        var hubConfiguration = new HubConfiguration
        { };
        
        map.RunSignalR(hubConfiguration);
    });
}
```

**Comment by webslayer** [comment]
hey, Startup.cs(38,35): error CS0246: The type or namespace name 'IAppBuilder' could not be found (are you missing a using directive or an assembly reference?) [/home/ubuntu/GAPITA/Gapita.csproj]

**Comment by ehsan-mohammadi** [comment]
Try to add these namespaces:

```csharp
using Microsoft.Owin;
using Microsoft.Owin.Cors;
using Owin;
```
