### ISSUE TITLE
Application returns 404 after start.

### ISSUE THREAD

**Issue by ankitsnlq** [ehsan-mohammadi/GAPITA#40]
Hi Ehsan, 

You might able to help me with setup. I tried to run this on Ubuntu 18.04. Done git clone and install dot net version 2.2.207 and node version v8.17.0. One I run `npm run release` I get error as follows. 

`npm run release`

```
> Gapita@1.0.0 release /home/ubuntu/files/GAPITA
> webpack --mode=production

clean-webpack-plugin: /home/ubuntu/files/GAPITA/wwwroot/* has been removed.
Hash: 7d7eac90839aa599ca54
Version: webpack 4.29.3
Time: 3333ms
Built at: 2020-04-25 07:10:04
 5 assets
Entrypoint eventfunc = eventfunc.js
Entrypoint indexfunc = indexfunc.js
Entrypoint chatfunc = chatfunc.js
Entrypoint aboutfunc = aboutfunc.js
Entrypoint errorfunc = errorfunc.js
 [9] (webpack)/buildin/global.js 472 bytes {0} {1} {2} {4} [built]
[13] ./node_modules/@aspnet/signalr/dist/esm/index.js + 14 modules 131 KiB {0} {1} {2} {4} [built]
     |    15 modules
[14] ./src/eventfunc.ts 2.27 KiB {3} [built]
[16] ./src/indexfunc.ts 1.17 KiB {4} [built]
[17] ./src/chatfunc.ts 12.7 KiB {1} [built] [1 error]
[18] ./src/aboutfunc.ts 1.84 KiB {0} [built]
[19] ./src/errorfunc.ts 1.17 KiB {2} [built]
    + 13 hidden modules

ERROR in ./src/chatfunc.ts
Module not found: Error: Can't resolve 'Jquery' in '/home/ubuntu/files/GAPITA/src'
 @ ./src/chatfunc.ts 4:8-25

ERROR in /home/ubuntu/files/GAPITA/src/chatfunc.ts
./src/chatfunc.ts
[tsl] ERROR in /home/ubuntu/files/GAPITA/src/chatfunc.ts(2,20)
      TS2307: Cannot find module 'Jquery'.
Child HtmlWebpackCompiler:
     4 assets
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_1 = __child-HtmlWebpackPlugin_1
    Entrypoint HtmlWebpackPlugin_2 = __child-HtmlWebpackPlugin_2
    Entrypoint HtmlWebpackPlugin_3 = __child-HtmlWebpackPlugin_3
    [1] (webpack)/buildin/global.js 472 bytes {0} {1} {2} {3} [built]
    [2] (webpack)/buildin/module.js 497 bytes {0} {1} {2} {3} [built]
    [3] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 8.85 KiB {0} [built]
    [4] ./node_modules/html-webpack-plugin/lib/loader.js!./src/chat.html 17.4 KiB {1} [built]
    [5] ./node_modules/html-webpack-plugin/lib/loader.js!./src/about.html 6.29 KiB {2} [built]
    [6] ./node_modules/html-webpack-plugin/lib/loader.js!./src/error.html 4.18 KiB {3} [built]
        + 1 hidden module
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! Gapita@1.0.0 release: `webpack --mode=production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the Gapita@1.0.0 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-04-25T07_10_04_304Z-debug.log

```

When I start dotnet server using dotnet run command url http://localhost:5000 returns 404. Check dotnet run log. 

`dotnet run
Hosting environment: Development
Content root path: /home/ubuntu/files/GAPITA
Now listening on: https://localhost:5001
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.0 GET http://3.133.194.60/  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 31.8551ms 404 
^CApplication is shutting down...
`

**Comment by ehsan-mohammadi** [comment]
Hi and sorry for the delay. 

At first, make sure you installed `jQuery`:

```
npm install jquery
```

Also, I think Linux is case-sensitive. So, try to change `import * as $ from "Jquery";` to `import * as $ from "jquery";` in `chatfunc.ts` file.

https://github.com/ehsan-mohammadi/GAPITA/blob/5653e5713477c1311c32c1a3df4e38aa03062b20/src/chatfunc.ts#L2

Hope it helps you.

**Comment by ehsan-mohammadi** [comment]
Hi @ankitsnlq and sorry for the delay. 

At first, make sure you installed `jQuery`:

```
npm install jquery
```

Also, I think Linux is case-sensitive. So, try to change `import * as $ from "Jquery";` to `import * as $ from "jquery";` in `chatfunc.ts` file.

https://github.com/ehsan-mohammadi/GAPITA/blob/5653e5713477c1311c32c1a3df4e38aa03062b20/src/chatfunc.ts#L2

Hope it helps you.
