### ISSUE TITLE
For anyone out there trying to make this work in 2021

### ISSUE THREAD

**Issue by skysky2333** [ehsan-mohammadi/GAPITA#41]
Hi all so I'm kinda new to backend/frontend server/node.js and found this amazing piece and thought I could learn from it. After some hours I finally make it work on ubuntu 20.04LTS. I'm sure there's many out there like me who's just starting out so here are some problems I encountered along with their solutions:

1. there's a typo in chatfun.ts lead to an error in the release script, you need to change one of the import packages from "Jquery" to "jquery". This one took me the longest to figure out lol I've tried installing a dozen versions of jquery before realizing the typo.

2. Microsoft has stopped supporting Dotnet version 2.2 in 2019, so you need to install it manually by downloading the binary file from the Microsoft site (it's listed under "unsurpoted section" I think) and run the following command:

> mkdir -p $HOME/dotnet && tar xf dotnet-sdk-2.2.100-linux-x64.tar.gz -C $HOME/dotnet
export DOTNET_ROOT=$HOME/dotnet
export PATH=$PATH:$HOME/dotnet

It can be downgraded to version 2.1 fairy easily (I assume by reading official docs) but I'm certainly not skilled enough to do so haha.

3. for the same reason, you also need to install libssl1.0 since the default version is way newer. You can do it following this page: https://www.garron.me/en/linux/install-ruby-2-3-3-ubuntu.html. It's for old ruby but works for us too.

Hope that helps!

**Comment by ehsan-mohammadi** [comment]
Hi @skysky2333!

Thanks for your comment. That's so helpful! If you know how to contribute, you can do these changes and else, I'll fix them.

**Comment by ysakovs** [comment]
Hello! Do you fix them?

**Comment by ehsan-mohammadi** [comment]
Hi @ysakovs!
Unfortunately, I didn't fix these problems so far, but if you know how to contribute, you can fix them and send me your PR.

Good luck

**Comment by ysakovs** [comment]
Hi! Update for fix?

**Comment by ehsan-mohammadi** [comment]
@skysky2333, @ysakovs After a long time, I fixed the problems 😅
